name: Check Next Version

on:
  workflow_dispatch:

permissions: read-all

jobs:
  dev_deploy:
    name: Check App next version to be released
    if: ${{ github.repository == 'sws2apps/organized-app' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout for release preparation
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: main
          persist-credentials: false

      - name: Use Node.js LTS version
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: lts/Iron

      - name: Install package dependencies
        run: npm ci

      - name: Run Semantic Release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
