name: Rebuild Staging Environment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions: read-all

jobs:
  main:
    name: Deploy to Render
    environment:
      name: Staging
      url: https://staging.organized-app.com
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@d091bd29255c83fd1110cf4cd099561179480c7b
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
